Repository atlp-rwanda/bravo-bn-be, pull requests merged in 2022-05, with the labels that each got.

#6 Chore-deploy-heroku#182201713
  Procfile
  package.json
  src/index.js
Labels: Approved

#4 chore(doc):Setup API documentation using swagger
  .babelrc
  nodemon.json
  package-lock.json
  package.json
  src/Documentation/index.doc.js
  src/controller/testSwaggerController.js
  src/index.js
  src/routers/testSwaggerRouter.js
Labels: Ready for Review, Changes requested

#9 #182201659 [ configure-postgres-and-sequelize-ORM ]
  .babelrc
  .env.example
  .sequelizerc
  Procfile
  package-lock.json
  package.json
  src/app.js
  src/database/config/config.js
  src/database/migrations/20220523191126-create-users.js
  src/database/models/index.js
  src/database/models/users.js
  src/database/seeders/20220523193745-demo-user.js
  src/index.js
  src/routes/index.js
  src/routes/testSwaggerRouter.js
  src/routes/user.routes.js
  src/services/user.service.js
Labels: Ready for Review

#5 Chore/#182201658 setup project environment
  .babelrc
  .env.example
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/controllers/error.js
  src/controllers/userController.js
  src/database/db.config.js
  src/index.js
  src/middlewares/authorization.js
  src/modules/userModel.js
  src/routers/index.js
  src/routers/testSwaggerRouter.js
  src/routers/userRoute.js
  src/services/sendEmail.js
  src/tests/userTesr.js
  src/utils/appError.js
  src/utils/catchAsync.js
Labels: Ready for Review

#12 #182201663 Integrate Coveralls code coverage service
  .coveralls.yml
  .dockerignore
  .env.example
  .eslintrc.json
  .sequelizerc
  Dockerfile
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  src/app.js
  src/controllers/error.js
  src/controllers/users.js
  src/database/config/config.js
  src/database/migrations/20220519190438-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20220519202036-demo-users.js
  src/helpers/validation_schema.js
  src/routers/api/index.js
  src/routers/api/users.js
  src/routers/index.js
  src/utils/appError.js
  src/utils/catchAsync.js
  test/simple.test.js
Labels: Ready for Review, Approved
